<?php

namespace App\Models;

// use Illuminate\Database\Eloquent\Factories\HasFactory;
// use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;

// use Laravel\Sanctum\HasApiTokens;

class Event extends Model
{

    protected $table = 'managed_events';

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function($model){
            $eventID = $model->id;

            $sectionTitles = ['South Upper', 'North Upper', 'NE Lower', 'N Lower', 'W Lower', 'S Lower'];
            foreach($sectionTitles as $sectionTitle){
                EventSchedulingSections::create([
                    'eventID' => $eventID,
                    'sectionTitle' => $sectionTitle
                ]);
            }

        });

    }

    /*public function getScheduledAttribute(){
        return $this->attributes['scheduled'];
    }

    public function setScheduledAttribute($value){
        $this->attributes['scheduled'] = $value;
    }*/

//    protected $appends = ['scheduled'];


//protected $attributes = [
//    'scheduled'
//];

    protected $fillable = [
        'name',
        'start_date',
        'end_date',
        'start_time',
        'end_time',
        'number_of_shifts'
        //'managers'  //todo: Might require separate table
    ];

}
